name: CI

on:
  push:
  pull_request:

jobs:
  fuzz-smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install CLI deps
        working-directory: server
        run: |
          python -m pip install -U pip wheel setuptools
          pip install -e ".[dev]" schemathesis

      - name: Start services (Docker Compose)
        working-directory: server
        run: |
          docker compose up -d --build
          # Vänta tills servern lyssnar på port 5000 (vi accepterar 200 eller 503)
          for i in {1..60}; do
            code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/healthz || true)
            if [ "$code" = "200" ] || [ "$code" = "503" ]; then
              echo "Server up (healthz=$code)"
              break
            fi
            sleep 2
          done

      - name: Run Schemathesis smoke fuzz
        working-directory: server
        env:
          TEST_HTTP_BASE: "http://localhost:5000"
        run: |
          mkdir -p fuzz
          ./fuzz/run-smoke.sh
        continue-on-error: true   # ✅ låt jobben fortsätta även om fuzz hittar fel

      - name: Collect docker logs
        if: always()
        working-directory: server
        run: |
          docker compose ps > fuzz/compose-ps.txt || true
          docker compose logs --no-color > fuzz/docker-logs.txt || true

      - name: Upload fuzz artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-artifacts
          path: |
            server/fuzz/junit-smoke.xml
            server/fuzz/fuzz.har
            server/fuzz/docker-logs.txt
            server/fuzz/compose-ps.txt
          retention-days: 14

